### ISSUE TITLE
Stream Deck MK.2 is now on sale.

### ISSUE THREAD

**Issue by jdahlblom** [OpenMacroBoard/StreamDeckSharp#35]
The PID is 0x0080 for it according to a user of my software. (15 button deck)
I can't find any info looking at databases although here it is mentioned : https://packagegalaxy.com/javascript/elgato-stream-deck

**Comment by jdahlblom** [comment]
```System.NullReferenceException
Object reference not set to an instance of an object.
   at StreamDeckSharp.Internals.BasicHidClient..ctor(IStreamDeckHid deckHid, IHardwareInternalInfos hardwareInformation)
   at StreamDeckSharp.StreamDeck.FromHid(HidDevice device, Boolean cached)
   at NonVisuals.StreamDeck.StreamDeckPanel..ctor(GamingPanelEnum panelType, HIDSkeleton hidSkeleton)
   at DCSFlightpanels.PanelUserControls.StreamDeckUserControl..ctor(GamingPanelEnum panelType, HIDSkeleton hidSkeleton, TabItem parentTabItem, IGlobalHandler globalHandler, DCSBIOS dcsbios)
   at DCSFlightpanels.MainWindow.SearchForPanels()```

**Comment by jdahlblom** [comment]
![2021-08-31_195352](https://user-images.githubusercontent.com/10453261/131544369-984407e8-1b8f-4dea-beda-dfa97aca069d.png)
